- name : Create VM's by invoking CFME API
  hosts: localhost
  connection: local
  ignore_errors: yes
  tasks:
  - name: Import ICS Pool role
    import_role:
      name: ./ics-pool

  - name: Import cfme-vms role
    import_role:
      name: ./cfme-vms
    vars:
      - ics_small_count: "{{ num_of_vms.ansible_facts.ics_small_count }}"
      - ics_medium_count: "{{ num_of_vms.ansible_facts.ics_medium_count }}"
      - ics_large_count: "{{ num_of_vms.ansible_facts.ics_large_count }}"

